/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.ColoniaKey;
import modelo.Colonia;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.ColoniaDAO;

/**
 * This class provides methods to populate DB Table of Colonia
 */
public class ColoniaDAOImpl implements ColoniaDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Colonia ("
        + "nombreDelegacion, nombreColonia"
        + ") VALUES (?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "nombreDelegacion, nombreColonia "
        + "FROM Colonia WHERE "
        + "nombreColonia = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Colonia SET "
        + "nombreDelegacion = ? "
        + "WHERE "
        + "nombreColonia = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Colonia WHERE "
        + "nombreColonia = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Colonia bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getNombredelegacion());
            ps.setString(2, bean.getNombrecolonia());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Colonia load(ColoniaKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getNombrecolonia());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Colonia) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Colonia bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getNombredelegacion());
            ps.setString(2, bean.getNombrecolonia());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(ColoniaKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getNombrecolonia());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Colonia> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Colonia>();
        while (rs.next()) {
            Colonia bean = new Colonia();
            bean.setNombredelegacion(rs.getString("nombreDelegacion"));
            bean.setNombrecolonia(rs.getString("nombreColonia"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}