/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.EquipoKey;
import modelo.Equipo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.EquipoDAO;

/**
 * This class provides methods to populate DB Table of Equipo
 */
public class EquipoDAOImpl implements EquipoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Equipo ("
        + "nombre, propietarioCURP, coachCURP, estadio"
        + ") VALUES (?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "nombre, propietarioCURP, coachCURP, estadio "
        + "FROM Equipo WHERE "
        + "nombre = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Equipo SET "
        + "propietarioCURP = ?, coachCURP = ?, estadio = ? "
        + "WHERE "
        + "nombre = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Equipo WHERE "
        + "nombre = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Equipo bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getNombre());
            ps.setString(2, bean.getPropietariocurp());
            ps.setString(3, bean.getCoachcurp());
            ps.setString(4, bean.getEstadio());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Equipo load(EquipoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getNombre());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Equipo) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Equipo bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getPropietariocurp());
            ps.setString(2, bean.getCoachcurp());
            ps.setString(3, bean.getEstadio());
            ps.setString(4, bean.getNombre());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(EquipoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getNombre());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Equipo> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Equipo>();
        while (rs.next()) {
            Equipo bean = new Equipo();
            bean.setNombre(rs.getString("nombre"));
            bean.setPropietariocurp(rs.getString("propietarioCURP"));
            bean.setCoachcurp(rs.getString("coachCURP"));
            bean.setEstadio(rs.getString("estadio"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}