/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.Estadio;
import modelo.EstadioKey;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.EstadioDAO;

/**
 * This class provides methods to populate DB Table of Estadio
 */
public class EstadioDAOImpl implements EstadioDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Estadio ("
        + "nombreEstadio, calle, capacidad"
        + ") VALUES (?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "nombreEstadio, calle, capacidad "
        + "FROM Estadio WHERE "
        + "nombreEstadio = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Estadio SET "
        + "calle = ?, capacidad = ? "
        + "WHERE "
        + "nombreEstadio = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Estadio WHERE "
        + "nombreEstadio = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Estadio bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getNombreestadio());
            ps.setString(2, bean.getCalle());
            ps.setInt(3, bean.getCapacidad());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Estadio load(EstadioKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getNombreestadio());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Estadio) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Estadio bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getCalle());
            ps.setInt(2, bean.getCapacidad());
            ps.setString(3, bean.getNombreestadio());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(EstadioKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getNombreestadio());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Estadio> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Estadio>();
        while (rs.next()) {
            Estadio bean = new Estadio();
            bean.setNombreestadio(rs.getString("nombreEstadio"));
            bean.setCalle(rs.getString("calle"));
            bean.setCapacidad(rs.getInt("capacidad"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}