/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.JugadorKey;
import modelo.Jugador;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.JugadorDAO;

/**
 * This class provides methods to populate DB Table of Jugador
 */
public class JugadorDAOImpl implements JugadorDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Jugador ("
        + "CURP, posicion, numero, salario, nombreEquipo, bajaPorLesion"
        + ") VALUES (?, ?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "CURP, posicion, numero, salario, nombreEquipo, bajaPorLesion "
        + "FROM Jugador WHERE "
        + "CURP = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Jugador SET "
        + "posicion = ?, numero = ?, salario = ?, nombreEquipo = ?, bajaPorLesion = ? "
        + "WHERE "
        + "CURP = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Jugador WHERE "
        + "CURP = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Jugador bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getCurp());
            ps.setString(2, bean.getPosicion());
            ps.setInt(3, bean.getNumero());
            ps.setDouble(4, bean.getSalario());
            ps.setString(5, bean.getNombreequipo());
            ps.setByte(6, bean.getBajaporlesion());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Jugador load(JugadorKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getCurp());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Jugador) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Jugador bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getPosicion());
            ps.setInt(2, bean.getNumero());
            ps.setDouble(3, bean.getSalario());
            ps.setString(4, bean.getNombreequipo());
            ps.setByte(5, bean.getBajaporlesion());
            ps.setString(6, bean.getCurp());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(JugadorKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getCurp());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Jugador> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Jugador>();
        while (rs.next()) {
            Jugador bean = new Jugador();
            bean.setCurp(rs.getString("CURP"));
            bean.setPosicion(rs.getString("posicion"));
            bean.setNumero(rs.getInt("numero"));
            bean.setSalario(rs.getDouble("salario"));
            bean.setNombreequipo(rs.getString("nombreEquipo"));
            bean.setBajaporlesion(rs.getByte("bajaPorLesion"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}