/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.Partido;
import modelo.PartidoKey;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.PartidoDAO;

/**
 * This class provides methods to populate DB Table of Partido
 */
public class PartidoDAOImpl implements PartidoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Partido ("
        + "equipoLocal, equipoVisitante, marcadorLocal, marcadorVisitante, temporada, noJornada"
        + ") VALUES (?, ?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "equipoLocal, equipoVisitante, marcadorLocal, marcadorVisitante, temporada, noJornada "
        + "FROM Partido WHERE "
        + "equipoLocal = ? AND equipoVisitante = ? AND temporada = ? AND noJornada = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Partido SET "
        + "marcadorLocal = ?, marcadorVisitante = ? "
        + "WHERE "
        + "equipoLocal = ? AND equipoVisitante = ? AND temporada = ? AND noJornada = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Partido WHERE "
        + "equipoLocal = ? AND equipoVisitante = ? AND temporada = ? AND noJornada = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Partido bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getEquipolocal());
            ps.setString(2, bean.getEquipovisitante());
            ps.setInt(3, bean.getMarcadorlocal());
            ps.setInt(4, bean.getMarcadorvisitante());
            ps.setString(5, bean.getTemporada());
            ps.setInt(6, bean.getNojornada());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Partido load(PartidoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getEquipolocal());
            ps.setString(2, key.getEquipovisitante());
            ps.setString(3, key.getTemporada());
            ps.setInt(4, key.getNojornada());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Partido) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Partido bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setInt(1, bean.getMarcadorlocal());
            ps.setInt(2, bean.getMarcadorvisitante());
            ps.setString(3, bean.getEquipolocal());
            ps.setString(4, bean.getEquipovisitante());
            ps.setString(5, bean.getTemporada());
            ps.setInt(6, bean.getNojornada());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(PartidoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getEquipolocal());
            ps.setString(2, key.getEquipovisitante());
            ps.setString(3, key.getTemporada());
            ps.setInt(4, key.getNojornada());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Partido> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Partido>();
        while (rs.next()) {
            Partido bean = new Partido();
            bean.setEquipolocal(rs.getString("equipoLocal"));
            bean.setEquipovisitante(rs.getString("equipoVisitante"));
            bean.setMarcadorlocal(rs.getInt("marcadorLocal"));
            bean.setMarcadorvisitante(rs.getInt("marcadorVisitante"));
            bean.setTemporada(rs.getString("temporada"));
            bean.setNojornada(rs.getInt("noJornada"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}