/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Articulo
 */
public class Articulo implements java.io.Serializable, Cloneable {
    private ArticuloKey _key = new ArticuloKey();

    /* categoria */
    protected String categoria;

    /* proveedor, PK */
    protected String proveedor;

    /* nombre, PK */
    protected String nombre;

    /* precio */
    protected double precio;

    /* Return the key object. */
    public ArticuloKey getKeyObject() {
        return _key;
    }

    /* categoria */
    public String getCategoria() {
        return categoria;
    }

    /* categoria */
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    /* proveedor, PK */
    public String getProveedor() {
        return proveedor;
    }

    /* proveedor, PK */
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
        _key.setProveedor(proveedor);
    }

    /* nombre, PK */
    public String getNombre() {
        return nombre;
    }

    /* nombre, PK */
    public void setNombre(String nombre) {
        this.nombre = nombre;
        _key.setNombre(nombre);
    }

    /* precio */
    public double getPrecio() {
        return precio;
    }

    /* precio */
    public void setPrecio(double precio) {
        this.precio = precio;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Articulo))
            return false;

        Articulo bean = (Articulo) obj;

        if (this.categoria == null) {
            if (bean.categoria != null)
                return false;
        }
        else if (!this.categoria.equals(bean.categoria)) 
            return false;

        if (this.proveedor == null) {
            if (bean.proveedor != null)
                return false;
        }
        else if (!this.proveedor.equals(bean.proveedor)) 
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.precio != bean.precio)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Articulo bean = new Articulo();
        bean.categoria = this.categoria;
        bean.proveedor = this.proveedor;
        bean.nombre = this.nombre;
        bean.precio = this.precio;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("categoria").append(" = ").append(categoria).append("]").append(sep);
        sb.append("[").append("proveedor").append(" = ").append(proveedor).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("precio").append(" = ").append(precio).append("]").append(sep);
        return sb.toString();
    }
}