/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table BonoEMpleado
 */
public class Bonoempleado implements java.io.Serializable, Cloneable {
    private BonoempleadoKey _key = new BonoempleadoKey();

    /* CURP, PK */
    protected String curp;

    /* fecha, PK */
    protected java.util.Date fecha;

    /* monto */
    protected double monto;

    /* Return the key object. */
    public BonoempleadoKey getKeyObject() {
        return _key;
    }

    /* CURP, PK */
    public String getCurp() {
        return curp;
    }

    /* CURP, PK */
    public void setCurp(String curp) {
        this.curp = curp;
        _key.setCurp(curp);
    }

    /* fecha, PK */
    public java.util.Date getFecha() {
        return fecha;
    }

    /* fecha, PK */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
        _key.setFecha(fecha);
    }

    /* monto */
    public double getMonto() {
        return monto;
    }

    /* monto */
    public void setMonto(double monto) {
        this.monto = monto;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Bonoempleado))
            return false;

        Bonoempleado bean = (Bonoempleado) obj;

        if (this.curp == null) {
            if (bean.curp != null)
                return false;
        }
        else if (!this.curp.equals(bean.curp)) 
            return false;

        if (this.fecha == null) {
            if (bean.fecha != null)
                return false;
        }
        else if (!this.fecha.equals(bean.fecha)) 
            return false;

        if (this.monto != bean.monto)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Bonoempleado bean = new Bonoempleado();
        bean.curp = this.curp;
        if (this.fecha != null)
            bean.fecha = (java.util.Date) this.fecha.clone();
        bean.monto = this.monto;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("curp").append(" = ").append(curp).append("]").append(sep);
        sb.append("[").append("fecha").append(" = ").append(fecha).append("]").append(sep);
        sb.append("[").append("monto").append(" = ").append(monto).append("]").append(sep);
        return sb.toString();
    }
}