/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class BonoempleadoKey implements java.io.Serializable, Cloneable {
    /* CURP */
    protected String curp;

    /* fecha */
    protected java.util.Date fecha;

    /* CURP */
    public String getCurp() {
        return curp;
    }

    /* CURP */
    public void setCurp(String curp) {
        this.curp = curp;
    }

    /* fecha */
    public java.util.Date getFecha() {
        return fecha;
    }

    /* fecha */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (curp != null)  
            hashCode += curp.hashCode();
        if (fecha != null)  
            hashCode += fecha.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof BonoempleadoKey))
            return false;

        BonoempleadoKey key = (BonoempleadoKey) obj;

        if (this.curp == null) {
            if (key.curp != null)
                return false;
        }
        else if (!this.curp.equals(key.curp)) 
            return false;

        if (this.fecha == null) {
            if (key.fecha != null)
                return false;
        }
        else if (!this.fecha.equals(key.fecha)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        BonoempleadoKey key = new BonoempleadoKey();
        key.curp = this.curp;
        if (this.fecha != null)
            key.fecha = (java.util.Date) this.fecha.clone();
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("curp").append(" = ").append(curp).append("]");
        sb.append("[").append("fecha").append(" = ").append(fecha).append("]");
        return sb.toString();
    }
}