/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class CalleKey implements java.io.Serializable, Cloneable {
    /* nombreCalle */
    protected String nombrecalle;

    /* nombreCalle */
    public String getNombrecalle() {
        return nombrecalle;
    }

    /* nombreCalle */
    public void setNombrecalle(String nombrecalle) {
        this.nombrecalle = nombrecalle;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (nombrecalle != null)  
            hashCode += nombrecalle.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CalleKey))
            return false;

        CalleKey key = (CalleKey) obj;

        if (this.nombrecalle == null) {
            if (key.nombrecalle != null)
                return false;
        }
        else if (!this.nombrecalle.equals(key.nombrecalle)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CalleKey key = new CalleKey();
        key.nombrecalle = this.nombrecalle;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombrecalle").append(" = ").append(nombrecalle).append("]");
        return sb.toString();
    }
}