/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Categoria
 */
public class Categoria implements java.io.Serializable, Cloneable {
    private CategoriaKey _key = new CategoriaKey();

    /* categoria, PK */
    protected String categoria;

    /* descripcion */
    protected String descripcion;

    /* Return the key object. */
    public CategoriaKey getKeyObject() {
        return _key;
    }

    /* categoria, PK */
    public String getCategoria() {
        return categoria;
    }

    /* categoria, PK */
    public void setCategoria(String categoria) {
        this.categoria = categoria;
        _key.setCategoria(categoria);
    }

    /* descripcion */
    public String getDescripcion() {
        return descripcion;
    }

    /* descripcion */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Categoria))
            return false;

        Categoria bean = (Categoria) obj;

        if (this.categoria == null) {
            if (bean.categoria != null)
                return false;
        }
        else if (!this.categoria.equals(bean.categoria)) 
            return false;

        if (this.descripcion == null) {
            if (bean.descripcion != null)
                return false;
        }
        else if (!this.descripcion.equals(bean.descripcion)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Categoria bean = new Categoria();
        bean.categoria = this.categoria;
        bean.descripcion = this.descripcion;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("categoria").append(" = ").append(categoria).append("]").append(sep);
        sb.append("[").append("descripcion").append(" = ").append(descripcion).append("]").append(sep);
        return sb.toString();
    }
}