/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class CiudadKey implements java.io.Serializable, Cloneable {
    /* nombreCiudad */
    protected String nombreciudad;

    /* nombreCiudad */
    public String getNombreciudad() {
        return nombreciudad;
    }

    /* nombreCiudad */
    public void setNombreciudad(String nombreciudad) {
        this.nombreciudad = nombreciudad;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (nombreciudad != null)  
            hashCode += nombreciudad.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CiudadKey))
            return false;

        CiudadKey key = (CiudadKey) obj;

        if (this.nombreciudad == null) {
            if (key.nombreciudad != null)
                return false;
        }
        else if (!this.nombreciudad.equals(key.nombreciudad)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CiudadKey key = new CiudadKey();
        key.nombreciudad = this.nombreciudad;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombreciudad").append(" = ").append(nombreciudad).append("]");
        return sb.toString();
    }
}