/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class ColoniaKey implements java.io.Serializable, Cloneable {
    /* nombreColonia */
    protected String nombrecolonia;

    /* nombreColonia */
    public String getNombrecolonia() {
        return nombrecolonia;
    }

    /* nombreColonia */
    public void setNombrecolonia(String nombrecolonia) {
        this.nombrecolonia = nombrecolonia;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (nombrecolonia != null)  
            hashCode += nombrecolonia.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof ColoniaKey))
            return false;

        ColoniaKey key = (ColoniaKey) obj;

        if (this.nombrecolonia == null) {
            if (key.nombrecolonia != null)
                return false;
        }
        else if (!this.nombrecolonia.equals(key.nombrecolonia)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        ColoniaKey key = new ColoniaKey();
        key.nombrecolonia = this.nombrecolonia;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombrecolonia").append(" = ").append(nombrecolonia).append("]");
        return sb.toString();
    }
}