/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:22 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Colonia
 */
public class Colonia implements java.io.Serializable, Cloneable {
    private ColoniaKey _key = new ColoniaKey();

    /* nombreDelegacion */
    protected String nombredelegacion;

    /* nombreColonia, PK */
    protected String nombrecolonia;

    /* Return the key object. */
    public ColoniaKey getKeyObject() {
        return _key;
    }

    /* nombreDelegacion */
    public String getNombredelegacion() {
        return nombredelegacion;
    }

    /* nombreDelegacion */
    public void setNombredelegacion(String nombredelegacion) {
        this.nombredelegacion = nombredelegacion;
    }

    /* nombreColonia, PK */
    public String getNombrecolonia() {
        return nombrecolonia;
    }

    /* nombreColonia, PK */
    public void setNombrecolonia(String nombrecolonia) {
        this.nombrecolonia = nombrecolonia;
        _key.setNombrecolonia(nombrecolonia);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Colonia))
            return false;

        Colonia bean = (Colonia) obj;

        if (this.nombredelegacion == null) {
            if (bean.nombredelegacion != null)
                return false;
        }
        else if (!this.nombredelegacion.equals(bean.nombredelegacion)) 
            return false;

        if (this.nombrecolonia == null) {
            if (bean.nombrecolonia != null)
                return false;
        }
        else if (!this.nombrecolonia.equals(bean.nombrecolonia)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Colonia bean = new Colonia();
        bean.nombredelegacion = this.nombredelegacion;
        bean.nombrecolonia = this.nombrecolonia;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombredelegacion").append(" = ").append(nombredelegacion).append("]").append(sep);
        sb.append("[").append("nombrecolonia").append(" = ").append(nombrecolonia).append("]").append(sep);
        return sb.toString();
    }
}