/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class DelegacionKey implements java.io.Serializable, Cloneable {
    /* nombreDelegacion */
    protected String nombredelegacion;

    /* nombreDelegacion */
    public String getNombredelegacion() {
        return nombredelegacion;
    }

    /* nombreDelegacion */
    public void setNombredelegacion(String nombredelegacion) {
        this.nombredelegacion = nombredelegacion;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (nombredelegacion != null)  
            hashCode += nombredelegacion.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof DelegacionKey))
            return false;

        DelegacionKey key = (DelegacionKey) obj;

        if (this.nombredelegacion == null) {
            if (key.nombredelegacion != null)
                return false;
        }
        else if (!this.nombredelegacion.equals(key.nombredelegacion)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        DelegacionKey key = new DelegacionKey();
        key.nombredelegacion = this.nombredelegacion;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombredelegacion").append(" = ").append(nombredelegacion).append("]");
        return sb.toString();
    }
}