/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Delegacion
 */
public class Delegacion implements java.io.Serializable, Cloneable {
    private DelegacionKey _key = new DelegacionKey();

    /* nombreCiudad */
    protected String nombreciudad;

    /* nombreDelegacion, PK */
    protected String nombredelegacion;

    /* Return the key object. */
    public DelegacionKey getKeyObject() {
        return _key;
    }

    /* nombreCiudad */
    public String getNombreciudad() {
        return nombreciudad;
    }

    /* nombreCiudad */
    public void setNombreciudad(String nombreciudad) {
        this.nombreciudad = nombreciudad;
    }

    /* nombreDelegacion, PK */
    public String getNombredelegacion() {
        return nombredelegacion;
    }

    /* nombreDelegacion, PK */
    public void setNombredelegacion(String nombredelegacion) {
        this.nombredelegacion = nombredelegacion;
        _key.setNombredelegacion(nombredelegacion);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Delegacion))
            return false;

        Delegacion bean = (Delegacion) obj;

        if (this.nombreciudad == null) {
            if (bean.nombreciudad != null)
                return false;
        }
        else if (!this.nombreciudad.equals(bean.nombreciudad)) 
            return false;

        if (this.nombredelegacion == null) {
            if (bean.nombredelegacion != null)
                return false;
        }
        else if (!this.nombredelegacion.equals(bean.nombredelegacion)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Delegacion bean = new Delegacion();
        bean.nombreciudad = this.nombreciudad;
        bean.nombredelegacion = this.nombredelegacion;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombreciudad").append(" = ").append(nombreciudad).append("]").append(sep);
        sb.append("[").append("nombredelegacion").append(" = ").append(nombredelegacion).append("]").append(sep);
        return sb.toString();
    }
}