/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Empleado
 */
public class Empleado implements java.io.Serializable, Cloneable {
    private EmpleadoKey _key = new EmpleadoKey();

    /* CURP, PK */
    protected String curp;

    /* puesto */
    protected String puesto;

    /* idTienda, PK */
    protected String idtienda;

    /* Return the key object. */
    public EmpleadoKey getKeyObject() {
        return _key;
    }

    /* CURP, PK */
    public String getCurp() {
        return curp;
    }

    /* CURP, PK */
    public void setCurp(String curp) {
        this.curp = curp;
        _key.setCurp(curp);
    }

    /* puesto */
    public String getPuesto() {
        return puesto;
    }

    /* puesto */
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }

    /* idTienda, PK */
    public String getIdtienda() {
        return idtienda;
    }

    /* idTienda, PK */
    public void setIdtienda(String idtienda) {
        this.idtienda = idtienda;
        _key.setIdtienda(idtienda);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Empleado))
            return false;

        Empleado bean = (Empleado) obj;

        if (this.curp == null) {
            if (bean.curp != null)
                return false;
        }
        else if (!this.curp.equals(bean.curp)) 
            return false;

        if (this.puesto == null) {
            if (bean.puesto != null)
                return false;
        }
        else if (!this.puesto.equals(bean.puesto)) 
            return false;

        if (this.idtienda == null) {
            if (bean.idtienda != null)
                return false;
        }
        else if (!this.idtienda.equals(bean.idtienda)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Empleado bean = new Empleado();
        bean.curp = this.curp;
        bean.puesto = this.puesto;
        bean.idtienda = this.idtienda;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("curp").append(" = ").append(curp).append("]").append(sep);
        sb.append("[").append("puesto").append(" = ").append(puesto).append("]").append(sep);
        sb.append("[").append("idtienda").append(" = ").append(idtienda).append("]").append(sep);
        return sb.toString();
    }
}