/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class EmpleadoKey implements java.io.Serializable, Cloneable {
    /* CURP */
    protected String curp;

    /* idTienda */
    protected String idtienda;

    /* CURP */
    public String getCurp() {
        return curp;
    }

    /* CURP */
    public void setCurp(String curp) {
        this.curp = curp;
    }

    /* idTienda */
    public String getIdtienda() {
        return idtienda;
    }

    /* idTienda */
    public void setIdtienda(String idtienda) {
        this.idtienda = idtienda;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (curp != null)  
            hashCode += curp.hashCode();
        if (idtienda != null)  
            hashCode += idtienda.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof EmpleadoKey))
            return false;

        EmpleadoKey key = (EmpleadoKey) obj;

        if (this.curp == null) {
            if (key.curp != null)
                return false;
        }
        else if (!this.curp.equals(key.curp)) 
            return false;

        if (this.idtienda == null) {
            if (key.idtienda != null)
                return false;
        }
        else if (!this.idtienda.equals(key.idtienda)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        EmpleadoKey key = new EmpleadoKey();
        key.curp = this.curp;
        key.idtienda = this.idtienda;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("curp").append(" = ").append(curp).append("]");
        sb.append("[").append("idtienda").append(" = ").append(idtienda).append("]");
        return sb.toString();
    }
}