/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class EstadioKey implements java.io.Serializable, Cloneable {
    /* nombreEstadio */
    protected String nombreestadio;

    /* nombreEstadio */
    public String getNombreestadio() {
        return nombreestadio;
    }

    /* nombreEstadio */
    public void setNombreestadio(String nombreestadio) {
        this.nombreestadio = nombreestadio;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (nombreestadio != null)  
            hashCode += nombreestadio.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof EstadioKey))
            return false;

        EstadioKey key = (EstadioKey) obj;

        if (this.nombreestadio == null) {
            if (key.nombreestadio != null)
                return false;
        }
        else if (!this.nombreestadio.equals(key.nombreestadio)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        EstadioKey key = new EstadioKey();
        key.nombreestadio = this.nombreestadio;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombreestadio").append(" = ").append(nombreestadio).append("]");
        return sb.toString();
    }
}