/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Estadio
 */
public class Estadio implements java.io.Serializable, Cloneable {
    private EstadioKey _key = new EstadioKey();

    /* nombreEstadio, PK */
    protected String nombreestadio;

    /* calle */
    protected String calle;

    /* capacidad */
    protected int capacidad;

    /* Return the key object. */
    public EstadioKey getKeyObject() {
        return _key;
    }

    /* nombreEstadio, PK */
    public String getNombreestadio() {
        return nombreestadio;
    }

    /* nombreEstadio, PK */
    public void setNombreestadio(String nombreestadio) {
        this.nombreestadio = nombreestadio;
        _key.setNombreestadio(nombreestadio);
    }

    /* calle */
    public String getCalle() {
        return calle;
    }

    /* calle */
    public void setCalle(String calle) {
        this.calle = calle;
    }

    /* capacidad */
    public int getCapacidad() {
        return capacidad;
    }

    /* capacidad */
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Estadio))
            return false;

        Estadio bean = (Estadio) obj;

        if (this.nombreestadio == null) {
            if (bean.nombreestadio != null)
                return false;
        }
        else if (!this.nombreestadio.equals(bean.nombreestadio)) 
            return false;

        if (this.calle == null) {
            if (bean.calle != null)
                return false;
        }
        else if (!this.calle.equals(bean.calle)) 
            return false;

        if (this.capacidad != bean.capacidad)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Estadio bean = new Estadio();
        bean.nombreestadio = this.nombreestadio;
        bean.calle = this.calle;
        bean.capacidad = this.capacidad;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombreestadio").append(" = ").append(nombreestadio).append("]").append(sep);
        sb.append("[").append("calle").append(" = ").append(calle).append("]").append(sep);
        sb.append("[").append("capacidad").append(" = ").append(capacidad).append("]").append(sep);
        return sb.toString();
    }
}