/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Jornada
 */
public class Jornada implements java.io.Serializable, Cloneable {
    private JornadaKey _key = new JornadaKey();

    /* temporada, PK */
    protected String temporada;

    /* noJornada, PK */
    protected int nojornada;

    /* fecha */
    protected java.util.Date fecha;

    /* Return the key object. */
    public JornadaKey getKeyObject() {
        return _key;
    }

    /* temporada, PK */
    public String getTemporada() {
        return temporada;
    }

    /* temporada, PK */
    public void setTemporada(String temporada) {
        this.temporada = temporada;
        _key.setTemporada(temporada);
    }

    /* noJornada, PK */
    public int getNojornada() {
        return nojornada;
    }

    /* noJornada, PK */
    public void setNojornada(int nojornada) {
        this.nojornada = nojornada;
        _key.setNojornada(nojornada);
    }

    /* fecha */
    public java.util.Date getFecha() {
        return fecha;
    }

    /* fecha */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Jornada))
            return false;

        Jornada bean = (Jornada) obj;

        if (this.temporada == null) {
            if (bean.temporada != null)
                return false;
        }
        else if (!this.temporada.equals(bean.temporada)) 
            return false;

        if (this.nojornada != bean.nojornada)
            return false;

        if (this.fecha == null) {
            if (bean.fecha != null)
                return false;
        }
        else if (!this.fecha.equals(bean.fecha)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Jornada bean = new Jornada();
        bean.temporada = this.temporada;
        bean.nojornada = this.nojornada;
        if (this.fecha != null)
            bean.fecha = (java.util.Date) this.fecha.clone();
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("temporada").append(" = ").append(temporada).append("]").append(sep);
        sb.append("[").append("nojornada").append(" = ").append(nojornada).append("]").append(sep);
        sb.append("[").append("fecha").append(" = ").append(fecha).append("]").append(sep);
        return sb.toString();
    }
}