/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Persona
 */
public class Persona implements java.io.Serializable, Cloneable {
    private PersonaKey _key = new PersonaKey();

    /* CURP, PK */
    protected String curp;

    /* nombre */
    protected String nombre;

    /* paterno */
    protected String paterno;

    /* materno */
    protected String materno;

    /* edad */
    protected int edad;

    /* fechaNacimiento */
    protected java.util.Date fechanacimiento;

    /* Return the key object. */
    public PersonaKey getKeyObject() {
        return _key;
    }

    /* CURP, PK */
    public String getCurp() {
        return curp;
    }

    /* CURP, PK */
    public void setCurp(String curp) {
        this.curp = curp;
        _key.setCurp(curp);
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* paterno */
    public String getPaterno() {
        return paterno;
    }

    /* paterno */
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }

    /* materno */
    public String getMaterno() {
        return materno;
    }

    /* materno */
    public void setMaterno(String materno) {
        this.materno = materno;
    }

    /* edad */
    public int getEdad() {
        return edad;
    }

    /* edad */
    public void setEdad(int edad) {
        this.edad = edad;
    }

    /* fechaNacimiento */
    public java.util.Date getFechanacimiento() {
        return fechanacimiento;
    }

    /* fechaNacimiento */
    public void setFechanacimiento(java.util.Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Persona))
            return false;

        Persona bean = (Persona) obj;

        if (this.curp == null) {
            if (bean.curp != null)
                return false;
        }
        else if (!this.curp.equals(bean.curp)) 
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.paterno == null) {
            if (bean.paterno != null)
                return false;
        }
        else if (!this.paterno.equals(bean.paterno)) 
            return false;

        if (this.materno == null) {
            if (bean.materno != null)
                return false;
        }
        else if (!this.materno.equals(bean.materno)) 
            return false;

        if (this.edad != bean.edad)
            return false;

        if (this.fechanacimiento == null) {
            if (bean.fechanacimiento != null)
                return false;
        }
        else if (!this.fechanacimiento.equals(bean.fechanacimiento)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Persona bean = new Persona();
        bean.curp = this.curp;
        bean.nombre = this.nombre;
        bean.paterno = this.paterno;
        bean.materno = this.materno;
        bean.edad = this.edad;
        if (this.fechanacimiento != null)
            bean.fechanacimiento = (java.util.Date) this.fechanacimiento.clone();
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("curp").append(" = ").append(curp).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("paterno").append(" = ").append(paterno).append("]").append(sep);
        sb.append("[").append("materno").append(" = ").append(materno).append("]").append(sep);
        sb.append("[").append("edad").append(" = ").append(edad).append("]").append(sep);
        sb.append("[").append("fechanacimiento").append(" = ").append(fechanacimiento).append("]").append(sep);
        return sb.toString();
    }
}