/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Proveedor
 */
public class Proveedor implements java.io.Serializable, Cloneable {
    private ProveedorKey _key = new ProveedorKey();

    /* nombre, PK */
    protected String nombre;

    /* ciudad */
    protected String ciudad;

    /* Return the key object. */
    public ProveedorKey getKeyObject() {
        return _key;
    }

    /* nombre, PK */
    public String getNombre() {
        return nombre;
    }

    /* nombre, PK */
    public void setNombre(String nombre) {
        this.nombre = nombre;
        _key.setNombre(nombre);
    }

    /* ciudad */
    public String getCiudad() {
        return ciudad;
    }

    /* ciudad */
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Proveedor))
            return false;

        Proveedor bean = (Proveedor) obj;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.ciudad == null) {
            if (bean.ciudad != null)
                return false;
        }
        else if (!this.ciudad.equals(bean.ciudad)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Proveedor bean = new Proveedor();
        bean.nombre = this.nombre;
        bean.ciudad = this.ciudad;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("ciudad").append(" = ").append(ciudad).append("]").append(sep);
        return sb.toString();
    }
}