/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class UsuarioKey implements java.io.Serializable, Cloneable {
    /* CURP */
    protected String curp;

    /* nombreUsuario */
    protected String nombreusuario;

    /* CURP */
    public String getCurp() {
        return curp;
    }

    /* CURP */
    public void setCurp(String curp) {
        this.curp = curp;
    }

    /* nombreUsuario */
    public String getNombreusuario() {
        return nombreusuario;
    }

    /* nombreUsuario */
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (curp != null)  
            hashCode += curp.hashCode();
        if (nombreusuario != null)  
            hashCode += nombreusuario.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof UsuarioKey))
            return false;

        UsuarioKey key = (UsuarioKey) obj;

        if (this.curp == null) {
            if (key.curp != null)
                return false;
        }
        else if (!this.curp.equals(key.curp)) 
            return false;

        if (this.nombreusuario == null) {
            if (key.nombreusuario != null)
                return false;
        }
        else if (!this.nombreusuario.equals(key.nombreusuario)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        UsuarioKey key = new UsuarioKey();
        key.curp = this.curp;
        key.nombreusuario = this.nombreusuario;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("curp").append(" = ").append(curp).append("]");
        sb.append("[").append("nombreusuario").append(" = ").append(nombreusuario).append("]");
        return sb.toString();
    }
}